"""initial schema

Creates all 13 tables from spec §16.3 plus the singleton `gmail_connection`
table for the shared GNC Gmail account.

Two foreign keys are added AFTER table creation because they form circular
dependencies with the referenced tables:
    * emails.ai_analysis_id → ai_analyses.id
      (ai_analyses.email_id already references emails.id)
    * invoice_drafts.approved_invoice_id → invoices.id
      (invoices.draft_id already references invoice_drafts.id)

Revision ID: 0001_initial_schema
Revises:
Create Date: auto-generated
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- Extensions ----
    # gen_random_uuid() is built-in in Postgres 13+, but pgcrypto guarantees it
    # in older versions too. IF NOT EXISTS makes this idempotent.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_legal_name', sa.String(length=255), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('primary_contact_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address_line1', sa.Text(), nullable=False),
    sa.Column('address_line2', sa.Text(), nullable=True),
    sa.Column('rate_strategy', sa.String(length=20), nullable=False),
    sa.Column('rate_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_terms', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_days', sa.Integer(), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=True),
    sa.Column('invoice_start_number', sa.Integer(), nullable=False),
    sa.Column('reset_yearly', sa.Boolean(), nullable=False),
    sa.Column('template_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("client_type IN ('Insurance', 'Adjuster', 'Contractor', 'Other')", name=op.f('ck_clients_client_type_valid')),
    sa.CheckConstraint("rate_strategy IN ('flat', 'tiered', 'fee_budget')", name=op.f('ck_clients_rate_strategy_valid')),
    sa.CheckConstraint('gst_percent >= 0 AND gst_percent <= 100', name=op.f('ck_clients_gst_percent_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index('ix_clients_active', 'clients', ['is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.create_table('gmail_connection',
    sa.Column('singleton_key', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('google_user_id', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_history_id', sa.String(length=64), nullable=True),
    sa.Column('connected_by_admin_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("singleton_key = 'default'", name=op.f('ck_gmail_connection_singleton_key_locked')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmail_connection')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_gmail_connection_singleton_key'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('google_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('Admin', 'PM', 'HourVerifier', 'RSApprover', 'User')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_active', 'users', ['is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('billing_rules',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('charge_type', sa.String(length=20), nullable=False),
    sa.Column('base_hours', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('flat_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=30), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_scope', sa.String(length=20), nullable=False),
    sa.Column('client_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(charge_type = 'hourly' AND base_hours IS NOT NULL) OR (charge_type = 'flat_fee' AND flat_fee IS NOT NULL) OR (charge_type = 'per_unit')", name=op.f('ck_billing_rules_charge_config_present')),
    sa.CheckConstraint("charge_type IN ('hourly', 'flat_fee', 'per_unit')", name=op.f('ck_billing_rules_charge_type_valid')),
    sa.CheckConstraint("client_scope IN ('global', 'client_specific')", name=op.f('ck_billing_rules_client_scope_valid')),
    sa.CheckConstraint("uom IN ('hrs', 'min', 'per_page', 'per_line', 'per_call', 'flat')", name=op.f('ck_billing_rules_uom_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_billing_rules_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_rules')),
    sa.UniqueConstraint('code', name=op.f('uq_billing_rules_code'))
    )
    op.create_index('ix_billing_rules_active', 'billing_rules', ['is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('ix_billing_rules_client_scope', 'billing_rules', ['client_scope'], unique=False)
    op.create_table('claims',
    sa.Column('gnc_file_no', sa.String(length=50), nullable=False),
    sa.Column('claim_no', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('insured_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loss_type', sa.String(length=50), nullable=False),
    sa.Column('date_of_loss', sa.Date(), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed')", name=op.f('ck_claims_status_valid')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_claims_client_id_clients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('client_id', 'claim_no', name='uq_claims_client_id_claim_no'),
    sa.UniqueConstraint('gnc_file_no', name=op.f('uq_claims_gnc_file_no'))
    )
    op.create_index('ix_claims_client_id', 'claims', ['client_id'], unique=False)
    op.create_index('ix_claims_file_name', 'claims', ['file_name'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('current_step_name', sa.String(length=100), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('estimated_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('invoice_search', 'backfill', 'gmail_sync')", name=op.f('ck_processing_jobs_job_type_valid')),
    sa.CheckConstraint("status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')", name=op.f('ck_processing_jobs_status_valid')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_processing_jobs_progress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_processing_jobs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index('ix_processing_jobs_celery_task_id', 'processing_jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_user_id', 'processing_jobs', ['user_id'], unique=False)
    op.create_table('emails',
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_link', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('to_emails', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cc_emails', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_path', sa.Text(), nullable=False),
    sa.Column('body_snippet', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_analysis_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_emails_claim_id_claims'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emails')),
    sa.UniqueConstraint('gmail_message_id', name=op.f('uq_emails_gmail_message_id'))
    )
    op.create_index('ix_emails_claim_id', 'emails', ['claim_id'], unique=False)
    op.create_index('ix_emails_content_hash', 'emails', ['content_hash'], unique=False)
    op.create_index('ix_emails_date', 'emails', ['date'], unique=False, postgresql_using='btree')
    op.create_index('ix_emails_gmail_thread_id', 'emails', ['gmail_thread_id'], unique=False)
    op.create_table('invoice_drafts',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('gnc_file_no', sa.String(length=50), nullable=False),
    sa.Column('client_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insured_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loss_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emails_reviewed', sa.Integer(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('duplicate_warning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('approved_invoice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'PENDING_PM', 'PENDING_HOUR_VERIFY', 'PENDING_RS', 'APPROVED', 'REJECTED')", name=op.f('ck_invoice_drafts_status_valid')),
    sa.CheckConstraint('billing_period_end >= billing_period_start', name=op.f('ck_invoice_drafts_billing_period_ordered')),
    sa.CheckConstraint('subtotal >= 0 AND grand_total >= 0', name=op.f('ck_invoice_drafts_totals_non_negative')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_invoice_drafts_claim_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_invoice_drafts_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invoice_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_invoice_drafts_job_id_processing_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_drafts'))
    )
    op.create_index('ix_invoice_drafts_claim_id', 'invoice_drafts', ['claim_id'], unique=False)
    op.create_index('ix_invoice_drafts_client_id', 'invoice_drafts', ['client_id'], unique=False)
    op.create_index('ix_invoice_drafts_created_by', 'invoice_drafts', ['created_by'], unique=False)
    op.create_index('ix_invoice_drafts_status', 'invoice_drafts', ['status'], unique=False)
    op.create_table('attachments',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('extracted_text_path', sa.Text(), nullable=True),
    sa.Column('extracted_text_snippet', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_applied', sa.Boolean(), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('pending', 'done', 'failed')", name=op.f('ck_attachments_extraction_status_valid')),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_attachments_file_size_non_negative')),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_attachments_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index('ix_attachments_email_id', 'attachments', ['email_id'], unique=False)
    op.create_index('ix_attachments_extraction_status', 'attachments', ['extraction_status'], unique=False)
    op.create_index('ix_attachments_file_hash', 'attachments', ['file_hash'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excel_path', sa.Text(), nullable=False),
    sa.Column('excel_file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_to_client_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('email_recipient', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence_avg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('emails_processed', sa.Integer(), nullable=False),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('manual_overrides', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('APPROVED', 'SENT', 'CANCELLED')", name=op.f('ck_invoices_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_invoices_amount_non_negative')),
    sa.CheckConstraint('billing_period_end >= billing_period_start', name=op.f('ck_invoices_billing_period_ordered')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_invoices_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_invoices_claim_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_invoices_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draft_id'], ['invoice_drafts.id'], name=op.f('fk_invoices_draft_id_invoice_drafts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_invoices_sent_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_no', name=op.f('uq_invoices_invoice_no'))
    )
    op.create_index('ix_invoices_approved_at', 'invoices', ['approved_at'], unique=False)
    op.create_index('ix_invoices_claim_id', 'invoices', ['claim_id'], unique=False)
    op.create_index('ix_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('input_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=True),
    sa.Column('recommended_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('invoice_description', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('should_flag', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("analysis_type IN ('email_classify', 'attachment_summary', 'description_rewrite', 'hours_recommend')", name=op.f('ck_ai_analyses_analysis_type_valid')),
    sa.CheckConstraint("confidence IN ('High', 'Medium', 'Low')", name=op.f('ck_ai_analyses_confidence_valid')),
    sa.CheckConstraint("provider IN ('claude', 'openai', 'gemini')", name=op.f('ck_ai_analyses_provider_valid')),
    sa.CheckConstraint('(email_id IS NOT NULL) <> (attachment_id IS NOT NULL)', name=op.f('ck_ai_analyses_target_exactly_one')),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], name=op.f('fk_ai_analyses_attachment_id_attachments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('fk_ai_analyses_email_id_emails'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses')),
    sa.UniqueConstraint('input_hash', name=op.f('uq_ai_analyses_input_hash'))
    )
    op.create_index('ix_ai_analyses_attachment_id', 'ai_analyses', ['attachment_id'], unique=False)
    op.create_index('ix_ai_analyses_email_id', 'ai_analyses', ['email_id'], unique=False)
    op.create_table('billing_ledger',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('hours_billed', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tier_name', sa.String(length=50), nullable=True),
    sa.Column('billed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_billed >= 0', name=op.f('ck_billing_ledger_hours_billed_non_negative')),
    sa.CheckConstraint('period_year >= 2000 AND period_year <= 2100', name=op.f('ck_billing_ledger_period_year_range')),
    sa.CheckConstraint('rate_applied >= 0', name=op.f('ck_billing_ledger_rate_applied_non_negative')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_billing_ledger_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_billing_ledger_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_billing_ledger_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_ledger'))
    )
    op.create_index('ix_billing_ledger_client_id_period_year', 'billing_ledger', ['client_id', 'period_year'], unique=False)
    op.create_index('ix_billing_ledger_invoice_id', 'billing_ledger', ['invoice_id'], unique=False)
    # ### end Alembic commands ###

    # ---- Post-hoc foreign keys (circular references) ----
    op.create_foreign_key(
        "fk_emails_ai_analysis_id_ai_analyses",
        "emails", "ai_analyses",
        ["ai_analysis_id"], ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_invoice_drafts_approved_invoice_id_invoices",
        "invoice_drafts", "invoices",
        ["approved_invoice_id"], ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # ---- Drop circular FKs first ----
    op.drop_constraint(
        "fk_invoice_drafts_approved_invoice_id_invoices",
        "invoice_drafts", type_="foreignkey",
    )
    op.drop_constraint(
        "fk_emails_ai_analysis_id_ai_analyses",
        "emails", type_="foreignkey",
    )

# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_billing_ledger_invoice_id', table_name='billing_ledger')
    op.drop_index('ix_billing_ledger_client_id_period_year', table_name='billing_ledger')
    op.drop_table('billing_ledger')
    op.drop_index('ix_ai_analyses_email_id', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_attachment_id', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_client_id', table_name='invoices')
    op.drop_index('ix_invoices_claim_id', table_name='invoices')
    op.drop_index('ix_invoices_approved_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_attachments_file_hash', table_name='attachments')
    op.drop_index('ix_attachments_extraction_status', table_name='attachments')
    op.drop_index('ix_attachments_email_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_invoice_drafts_status', table_name='invoice_drafts')
    op.drop_index('ix_invoice_drafts_created_by', table_name='invoice_drafts')
    op.drop_index('ix_invoice_drafts_client_id', table_name='invoice_drafts')
    op.drop_index('ix_invoice_drafts_claim_id', table_name='invoice_drafts')
    op.drop_table('invoice_drafts')
    op.drop_index('ix_emails_gmail_thread_id', table_name='emails')
    op.drop_index('ix_emails_date', table_name='emails', postgresql_using='btree')
    op.drop_index('ix_emails_content_hash', table_name='emails')
    op.drop_index('ix_emails_claim_id', table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_processing_jobs_user_id', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_celery_task_id', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_claims_file_name', table_name='claims')
    op.drop_index('ix_claims_client_id', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_billing_rules_client_scope', table_name='billing_rules')
    op.drop_index('ix_billing_rules_active', table_name='billing_rules', postgresql_where='is_active = TRUE')
    op.drop_table('billing_rules')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_active', table_name='users', postgresql_where='is_active = TRUE')
    op.drop_table('users')
    op.drop_table('gmail_connection')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_index('ix_clients_active', table_name='clients', postgresql_where='is_active = TRUE')
    op.drop_table('clients')
    # ### end Alembic commands ###

